-- 直播分析数据模型。原始直播指标与数据罗盘销售事实分开保存。

create table if not exists public.live_sessions (
    live_room_id text primary key,
    shop_name text not null,
    anchor_name text not null default '未维护主播',
    live_title text,
    start_time timestamptz not null,
    end_time timestamptz,
    duration_seconds integer not null default 0 check (duration_seconds >= 0),
    source_url text,
    source_collected_at timestamptz,
    imported_at timestamptz not null default now()
);

create table if not exists public.live_metrics (
    id bigint generated by default as identity primary key,
    live_room_id text not null references public.live_sessions(live_room_id) on delete cascade,
    module text not null,
    metric_name text not null,
    metric_value numeric,
    raw_value text,
    unit text,
    benchmark_value numeric,
    benchmark_raw text,
    comparison_display text,
    unique (live_room_id, module, metric_name)
);

create table if not exists public.live_product_mappings (
    shop_name text not null,
    product_id text not null,
    product_name text,
    style_code text,
    match_method text not null default 'name_regex',
    match_status text not null default 'auto_matched',
    confirmed boolean not null default false,
    updated_at timestamptz not null default now(),
    primary key (shop_name, product_id)
);

create table if not exists public.live_products (
    id bigint generated by default as identity primary key,
    live_room_id text not null references public.live_sessions(live_room_id) on delete cascade,
    product_id text not null,
    product_name text not null,
    style_code text,
    match_status text not null default 'unmatched',
    talk_count integer not null default 0,
    first_listed_at timestamptz,
    live_price numeric not null default 0,
    paid_amount numeric not null default 0,
    sold_units integer not null default 0,
    presale_orders integer not null default 0,
    click_users integer not null default 0,
    exposure_click_rate numeric,
    click_conversion_rate numeric,
    gmv_per_1000_exposure numeric,
    pre_ship_refund_orders integer not null default 0,
    pre_ship_refund_amount numeric not null default 0,
    pre_ship_refund_users integer not null default 0,
    pre_ship_refund_rate numeric,
    post_ship_refund_orders integer not null default 0,
    post_ship_refund_amount numeric not null default 0,
    post_ship_refund_users integer not null default 0,
    post_ship_refund_rate numeric,
    unique (live_room_id, product_id)
);

create index if not exists live_sessions_shop_start_idx
    on public.live_sessions (shop_name, start_time desc);
create index if not exists live_sessions_anchor_start_idx
    on public.live_sessions (anchor_name, start_time desc);
create index if not exists live_metrics_room_idx
    on public.live_metrics (live_room_id);
create index if not exists live_products_room_idx
    on public.live_products (live_room_id);
create index if not exists live_products_style_idx
    on public.live_products (style_code, live_room_id);

alter table public.live_sessions enable row level security;
alter table public.live_metrics enable row level security;
alter table public.live_product_mappings enable row level security;
alter table public.live_products enable row level security;

revoke all on table public.live_sessions from anon, authenticated;
revoke all on table public.live_metrics from anon, authenticated;
revoke all on table public.live_product_mappings from anon, authenticated;
revoke all on table public.live_products from anon, authenticated;
revoke all on sequence public.live_metrics_id_seq from anon, authenticated;
revoke all on sequence public.live_products_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.live_sessions to service_role;
grant select, insert, update, delete on table public.live_metrics to service_role;
grant select, insert, update, delete on table public.live_product_mappings to service_role;
grant select, insert, update, delete on table public.live_products to service_role;
grant usage, select on sequence public.live_metrics_id_seq to service_role;
grant usage, select on sequence public.live_products_id_seq to service_role;

comment on table public.live_sessions is '直播场次，一场直播一行';
comment on table public.live_metrics is '直播间整体指标，一场直播每项指标一行';
comment on table public.live_products is '直播商品表现，一场直播每个商品一行';
comment on table public.live_product_mappings is '店铺商品ID到货号的可复用映射';
