create table if not exists public.promotion_product_weekly (
    id bigint generated by default as identity primary key,
    week_start date not null,
    week_end date not null,
    shop_name text not null,
    product_id text not null,
    product_name text,
    style_code text not null,
    impressions numeric not null default 0,
    clicks numeric not null default 0,
    ctr numeric not null default 0,
    conversion_rate numeric not null default 0,
    spend numeric not null default 0,
    gross_gmv numeric not null default 0,
    gross_roi numeric not null default 0,
    gross_order_cost numeric not null default 0,
    user_paid_amount numeric not null default 0,
    platform_subsidy numeric not null default 0,
    net_roi numeric not null default 0,
    net_gmv numeric not null default 0,
    net_order_cost numeric not null default 0,
    net_settlement_rate numeric not null default 0,
    refund_rate_1h numeric not null default 0,
    source_file text,
    uploaded_at timestamptz not null default now(),
    constraint promotion_week_sunday check (extract(dow from week_start) = 0),
    constraint promotion_week_span check (week_end = week_start + 6),
    constraint promotion_product_weekly_unique unique (week_start, shop_name, product_id)
);

create index if not exists promotion_product_weekly_week_shop_idx
    on public.promotion_product_weekly (week_start, shop_name);
create index if not exists promotion_product_weekly_style_idx
    on public.promotion_product_weekly (style_code);

alter table public.promotion_product_weekly enable row level security;
revoke all on table public.promotion_product_weekly from anon, authenticated;
grant all on table public.promotion_product_weekly to service_role;
grant usage, select on sequence public.promotion_product_weekly_id_seq to service_role;
