create table if not exists public.inventory_import_batches (
  id uuid primary key default gen_random_uuid(),
  inventory_date date not null,
  source_file_name text not null,
  status text not null default 'importing' check (status in ('importing', 'completed', 'failed')),
  source_rows integer not null default 0,
  source_styles integer not null default 0,
  matched_styles integer not null default 0,
  skipped_styles integer not null default 0,
  saved_rows integer not null default 0,
  negative_rows integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.inventory_stock_staging (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.inventory_import_batches(id) on delete cascade,
  inventory_date date not null,
  style_code text not null,
  sku text not null,
  warehouse_code text not null default '',
  warehouse_name text not null,
  color_code text not null default '',
  color_name text not null default '',
  size_code text not null default '',
  size_name text not null default '',
  available_qty numeric not null default 0,
  unique(batch_id, warehouse_code, warehouse_name, sku)
);

create table if not exists public.inventory_stock_current (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.inventory_import_batches(id),
  inventory_date date not null,
  style_code text not null,
  sku text not null,
  warehouse_code text not null default '',
  warehouse_name text not null,
  color_code text not null default '',
  color_name text not null default '',
  size_code text not null default '',
  size_name text not null default '',
  available_qty numeric not null default 0,
  unique(warehouse_code, warehouse_name, sku)
);

create index if not exists idx_inventory_current_style
  on public.inventory_stock_current(style_code);
create index if not exists idx_inventory_current_date
  on public.inventory_stock_current(inventory_date);
create index if not exists idx_inventory_staging_batch
  on public.inventory_stock_staging(batch_id);

alter table public.inventory_import_batches enable row level security;
alter table public.inventory_stock_staging enable row level security;
alter table public.inventory_stock_current enable row level security;

drop policy if exists inventory_batches_anon_all on public.inventory_import_batches;
create policy inventory_batches_anon_all on public.inventory_import_batches
  for all to anon using (true) with check (true);
drop policy if exists inventory_staging_anon_all on public.inventory_stock_staging;
create policy inventory_staging_anon_all on public.inventory_stock_staging
  for all to anon using (true) with check (true);
drop policy if exists inventory_current_anon_read on public.inventory_stock_current;
drop policy if exists inventory_current_anon_all on public.inventory_stock_current;
create policy inventory_current_anon_all on public.inventory_stock_current
  for all to anon using (true) with check (true);

grant select, insert, update, delete on public.inventory_import_batches to anon;
grant select, insert, update, delete on public.inventory_stock_staging to anon;
grant select, insert, update, delete on public.inventory_stock_current to anon;
grant usage, select on all sequences in schema public to anon;

create or replace function public.finalize_inventory_batch(p_batch_id uuid)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_date date;
begin
  select inventory_date into v_date
  from public.inventory_import_batches
  where id = p_batch_id and status = 'importing'
  for update;

  if v_date is null then
    raise exception 'Inventory batch is missing or is not importing';
  end if;

  delete from public.inventory_stock_current;

  insert into public.inventory_stock_current (
    batch_id, inventory_date, style_code, sku,
    warehouse_code, warehouse_name,
    color_code, color_name, size_code, size_name, available_qty
  )
  select
    batch_id, inventory_date, style_code, sku,
    warehouse_code, warehouse_name,
    color_code, color_name, size_code, size_name, available_qty
  from public.inventory_stock_staging
  where batch_id = p_batch_id;

  delete from public.inventory_stock_staging where batch_id = p_batch_id;
  update public.inventory_import_batches
  set status = 'completed', completed_at = now()
  where id = p_batch_id;
end;
$$;

revoke execute on function public.finalize_inventory_batch(uuid) from public;
grant execute on function public.finalize_inventory_batch(uuid) to anon;

create or replace view public.inventory_style_summary
with (security_invoker = true)
as
select
  style_code,
  max(inventory_date) as inventory_date,
  sum(available_qty) as total_inventory,
  sum(available_qty) filter (where btrim(warehouse_name) = '总仓') as main_warehouse_inventory,
  count(distinct warehouse_name) as warehouse_count
from public.inventory_stock_current
group by style_code;

grant select on public.inventory_style_summary to anon;
