create table if not exists public.user_table_layouts (
    id bigint generated by default as identity primary key,
    username text not null,
    page_key text not null,
    table_key text not null,
    template_name text not null,
    config jsonb not null default '{}'::jsonb,
    is_default boolean not null default false,
    updated_at timestamptz not null default now(),
    unique (username, page_key, table_key, template_name)
);

create index if not exists user_table_layouts_lookup_idx
on public.user_table_layouts (username, page_key, table_key);

alter table public.user_table_layouts enable row level security;

drop policy if exists user_table_layouts_app_access on public.user_table_layouts;
create policy user_table_layouts_app_access
on public.user_table_layouts for all to anon, authenticated
using (true) with check (true);

grant select, insert, update, delete on public.user_table_layouts to anon, authenticated;
grant usage, select on sequence public.user_table_layouts_id_seq to anon, authenticated;
