create table if not exists public.promotion_product_daily (
    id bigint generated by default as identity primary key,
    report_date date not null,
    shop_name text not null,
    product_id text not null,
    product_name text,
    style_code text not null,
    impressions numeric not null default 0,
    clicks numeric not null default 0,
    ctr numeric not null default 0,
    conversion_rate numeric not null default 0,
    spend numeric not null default 0,
    gross_gmv numeric not null default 0,
    gross_orders numeric not null default 0,
    gross_roi numeric not null default 0,
    gross_order_cost numeric not null default 0,
    user_paid_amount numeric not null default 0,
    coupon_amount numeric not null default 0,
    platform_subsidy numeric not null default 0,
    source_file text,
    uploaded_at timestamptz not null default now(),
    constraint promotion_product_daily_unique unique (report_date, shop_name, product_id)
);
create index if not exists promotion_product_daily_date_shop_idx on public.promotion_product_daily (report_date, shop_name);
create index if not exists promotion_product_daily_style_idx on public.promotion_product_daily (style_code);
alter table public.promotion_product_daily enable row level security;
revoke delete, truncate, references, trigger on table public.promotion_product_daily from anon, authenticated;
grant select, insert, update on table public.promotion_product_daily to anon, authenticated;
grant all on table public.promotion_product_daily to service_role;
grant usage, select on sequence public.promotion_product_daily_id_seq to anon, authenticated, service_role;
drop policy if exists "promotion daily read" on public.promotion_product_daily;
create policy "promotion daily read" on public.promotion_product_daily for select to anon, authenticated using (true);
drop policy if exists "promotion daily insert" on public.promotion_product_daily;
create policy "promotion daily insert" on public.promotion_product_daily for insert to anon, authenticated with check (true);
drop policy if exists "promotion daily update" on public.promotion_product_daily;
create policy "promotion daily update" on public.promotion_product_daily for update to anon, authenticated using (true) with check (true);
