create table if not exists public.access_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    username text not null,
    event_type text not null check (event_type in ('login', 'login_failed', 'login_restored', 'logout', 'page_view')),
    success boolean not null default true,
    page_key text,
    page_title text,
    session_id uuid not null,
    ip_address text,
    user_agent text,
    details jsonb not null default '{}'::jsonb
);

create index if not exists access_logs_created_at_idx on public.access_logs (created_at desc);
create index if not exists access_logs_username_created_at_idx on public.access_logs (username, created_at desc);
create index if not exists access_logs_event_type_created_at_idx on public.access_logs (event_type, created_at desc);

alter table public.access_logs enable row level security;

revoke all on table public.access_logs from anon, authenticated;
grant insert, select on table public.access_logs to anon;
grant insert, select on table public.access_logs to authenticated;
grant usage, select on sequence public.access_logs_id_seq to anon, authenticated;

drop policy if exists "access_logs_insert" on public.access_logs;
create policy "access_logs_insert"
on public.access_logs for insert
to anon, authenticated
with check (true);

drop policy if exists "access_logs_select" on public.access_logs;
create policy "access_logs_select"
on public.access_logs for select
to anon, authenticated
using (true);
